name: CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Linting with Super-Linter
      uses: github/super-linter@v2
      env:
       DEFAULT_BRANCH: main
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run E2E Tests
      run: |
        # Ajoutez  les tests E2E 
