name: CI Workflow

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run E2E Tests
      run: |
        # Ajoutez r les tests E2E

    - name: Linting
      run: |
        # Ajoutez  le linter
